completed all three levels of read file
Zhiwutian/new-instructor-training-code-solutions pull request #12
Opened 2022-11-29 22:37 UTC by Zhiwutian

2022-11-29 23:01 UTC, thebearingedge requested changes

2022-11-29 23:01 UTC, thebearingedge commented on node-fs-readfile/cat.js
> +  }
We can't necessarily rely on the length, since assigning to an arbitrary index of an array increases its length.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/7432943/204667204-385372ed-9429-4b5a-9694-f113c5d79756.png">


The approach using the array is close, but you should instead increment a counter every time a file completes. Recursion is another option.

2022-11-29 23:10 UTC, Zhiwutian commented
<img width="1143" alt="Screen Shot 2022-11-29 at 3 01 23 PM" src="https://user-images.githubusercontent.com/29086306/204668450-327e208e-64e6-40b8-ab09-832bd34db7e4.png">

2022-11-30 00:30 UTC, thebearingedge approved these changes

2022-11-30 00:37 UTC, merged